### ISSUE TITLE
Feature: Lyrics and Annotations Display

### ISSUE THREAD

**Issue by kianlin** [Orbital-Mulgo/Project#11]
# Feature Title

Feature: Lyrics and Annotations Display

## Feature Description

This Feature will display the lyrics and annotations of the song that the user searched for.

## List of Tasks (Complete in order)

1. [ ] [Task 1: Search for relevant API](https://github.com/username/repository-name/issues/1)
2. [ ] [Task 2: Implement the functionality](https://github.com/username/repository-name/issues/2)
3. [ ] [Task 3: UI of the results display](https://github.com/username/repository-name/issues/2)
4. [ ] [Task 4: Integration of Frontend and Backend](https://github.com/username/repository-name/issues/2)
5. [ ] [Task 5: Testing](https://github.com/username/repository-name/issues/2)
