### ISSUE TITLE
Feature: Login and Registration

### ISSUE THREAD

**Issue by kianlin** [Orbital-Mulgo/Project#17]
# Feature Title

Feature: Login and Registration

## Feature Description

This feature will allow users to register for an account and login into the platform.

## List of Tasks (Complete in order)

1. [x] [Task 1: Basic project set-up](https://github.com/Orbital-Mulgo/Project/issues/18)
2. [x] [Task 2: Functionality of login and registration with authentication](https://github.com/Orbital-Mulgo/Project/issues/19)
3. [x] [Task 3: UI of the login and registration page](https://github.com/Orbital-Mulgo/Project/issues/20)
4. [x] [Task 4: Integration of the frontend and backend of login and registration function](https://github.com/Orbital-Mulgo/Project/issues/21)
5. [x] [Task 5: Testing and documentation](https://github.com/Orbital-Mulgo/Project/issues/22)

**Comment by kianlin** [comment]
**Note:** This is a backdated feature for tracking purposes. The [initial commit](https://github.com/Orbital-Mulgo/Project/commit/5822c468b4caf00653f79a4b4e78b1c1d2f53bfb) has resolved the issue.
