### ISSUE TITLE
Feature: Automated Testing

### ISSUE THREAD

**Issue by kianlin** [Orbital-Mulgo/Project#34]
# Feature Title

Feature: Automated Testing

## Feature Description

This feature will look to automate the testing done by the team. This will be done by adopting the Software Testing Life Cycle (STLC) framework.

## List of Tasks (Complete in order)

1. [ ] [Task 1: Requirement Analysis](https://github.com/Orbital-Mulgo/Project/issues/4)
2. [ ] [Task 2: Test Planning](https://github.com/Orbital-Mulgo/Project/issues/4)
3. [ ] [Task 3: Test Case Development](https://github.com/Orbital-Mulgo/Project/issues/4)
4. [ ] [Task 4: Test Environment Setup](https://github.com/Orbital-Mulgo/Project/issues/4)
5. [ ] [Task 5: Test Execution](https://github.com/Orbital-Mulgo/Project/issues/4)
6. [ ] [Task 6: Test Closure](https://github.com/Orbital-Mulgo/Project/issues/4)
7. [ ] [Task 7: Automation Integration](https://github.com/Orbital-Mulgo/Project/issues/4)
8. [ ] [Task 8: Documentation](https://github.com/Orbital-Mulgo/Project/issues/4)
