### ISSUE TITLE
Task: Issues Template

### ISSUE THREAD

**Issue by kianlin** [Orbital-Mulgo/Project#4]
# Issues Template

Task and Feature Issues Template

## Description

This is the template to submit any task issues and features issues for this project to ensure consistency.

### Issues Template

- **Issue Title.** Task/Feature: [Task/Feature Name]
- **Description.** Format consists of:
  - Task Title
  - Description
  - Linked to Main/Sub- Issue (Optional)
- **Assignees.** Click on the users to assign the issue to them.
- **Labels.** Can make use of existing labels or [custom create](https://github.com/Orbital-Mulgo/Project/labels). 
- **Projects.** Adding the issue to the project Kanban board created before, allowing the automation of the linking of the issue to the _"To-do"_ column of the board. Upon completion, the issue will be moved to the _"Completed"_ column.
- **Milestone.** Link the issue to a particular milestone, to track the progress based on a certain deadline.

### Feature Issue

![image](https://user-images.githubusercontent.com/65789711/121869791-fb1e6a00-cd34-11eb-95fc-3a0d267aff8d.png)

**Template:**

```
# Core Feature 1
Feature: Audio Recognition

## Description
This feature will allow the user to record the song (of up to 15 seconds) playing and recognise the song title and artist associated with this song in our database.

## List of Tasks (Complete in order)
- [ ] Task 1: Research on audio fingerprinting and its algorithms
- [ ] Task 2: Functionality of the audio recognition
- [ ] Task 3: UI of the audio recognition
- [ ] Task 4: Testing and performance analytics

```

### Task Issue

![image](https://user-images.githubusercontent.com/65789711/121870275-7718b200-cd35-11eb-8670-f061339bcf86.png)

```
# Task Title

Task: Research on audio fingerprinting and its algorithms

## Task Description

This task will look into the concepts of audio fingerprinting and the algorithms behind it. Relevant resources will be shared here.

## Main Issue
This task is part of [Feature: Audio Recognition](https://github.com/Orbital-Mulgo/Project/issues/1).

```
